### ISSUE TITLE
Figure out how to import inter(audio|video)(sink|src) into gst-switch

### ISSUE THREAD

**Issue by mithro** [timvideos/gst-switch#100]
gstreamer's inter plugin has gotten a lot of work and fixes recently. We want to continue to build on Ubuntu 14.04 until we can move to another LTS. @thaytan suggested we just import these plugins into gst-switch.

@thaytan can you give us advice on the best way to do this? It would be nice if we could have the following properties - however many might be not worth the effort...
- Keep some type of history information. IE When we "pull" the latest gstreamer version we preserve history of the changes in gstreamer (so we can easily track down changes).
- Able to make changes to plugins and then send the patches upstream after testing.

Have a shell script which;
- Adds gst-plugins-XXXX repo as a remote.
- Fetches the branch.
- Uses git-filter-branch to extract the relevant plugin.
- git merge the repo into third_party/plugins.
- automake runs a "sed -e's/xxx/xxx/'" on third_party/ and then we build that output.

**Comment by mithro** [comment]
@thaytan I have a tendency to over complicate things, is this plan stupid?

**Comment by thaytan** [comment]
I'd probably start with just copying over source files and keeping a README of which upstream commit was imported in a README, and if it ever needs updating, doing it with a diff from there. If you need to do that more than once, consider a more complicated import
