### ISSUE TITLE
Turning off the Stream without disturbing the Recording

### ISSUE THREAD

**Issue by MaZderMind** [timvideos/gst-switch#109]
In Pauses between Talks we often swich to a [Pause-Loop](http://c3voc.mazdermind.de/intro-outro-generator/sotmeu14/examples/pause.mp4). When using DVSwitch we only have one output which is recorded and live-streamed at the same time, so when selecting the Pause-Loop as Source it will also be recorded.

Often at the beginning of the next talk, the switch back to the camera source occures too late, so that final produced videos start with some seconds of Pause-Loop.

To avoid this it would be nice to configure a Pause-Loop and ideally also a Pause-Music which is looped separately. The GUI should them have an option to switch the Live-Stream output to Pause while keeping the rest of the switcher including the recording working.

This would also allow to explain the Usage of the GUI in Pauses between Talks without disturbing the Live-Stream users.

**Comment by MaZderMind** [comment]
As an addendum this would also be very useful for Events where a Live-Streaming is prohibited because of legal reasons (GEMA or sth. like this). It would be required to have another NoStream-Loop selectable in the GUI for this.

**Comment by mithro** [comment]
Having multiple "outputs" is really easy for the server - the only problem is the complexity in the UI.

This could currently be implemented by having a gst-switch stream which is doing the recording/mixing into a second gst-switch which does the switching for live feed output. That sounds a bit complicated though...

An alternative button would be to have a "go live" button which enables/disables the output video on the streaming port?

**Comment by MaZderMind** [comment]
yes, a ON AIR button was something I thought about (although in practice a NOT ON AIR button would be more useful). I also don't think there's a need to make this too deep configurable in my reality ;) there's only recording and streaming, so I'd hardcode those two outputs.

**Comment by mithro** [comment]
The UI in -> https://github.com/timvideos/gst-switch/pull/70 could have an on-air button added

**Comment by CarlFK** [comment]
Is this all because "the switch back to the camera source occures too late" ?

**Comment by MaZderMind** [comment]
It's because the people that do the mixing are not necessary part of our team and sometimes don't take recordings as important as we do, so often they arrive late and the speaker has already started talking.

Also sometimes sometimes speaker say "Hum - you're recording? I'm not sure if my boss allows this... Please don't stream me live and don't release the File until I asked him". Ofthen they allow releasing later on.

**Comment by mithro** [comment]
@CarlFK FYI, this is a feature request.
