### ISSUE TITLE
PIP Background Animation

### ISSUE THREAD

**Issue by MaZderMind** [timvideos/gst-switch#110]
On 31C3 we played with animated PIP Backgrounds and it looked very nice (see [here for an example](http://media.ccc.de/browse/congress/2014/31c3_-_6450_-_de_-_saal_1_-_201412272030_-_ich_sehe_also_bin_ich_du_-_starbug.html#video&t=336)).

This would best be configured as a separate Video-Input so that it can be changed & replaced without restarting the Server.

**Comment by mithro** [comment]
The first step here would be to build a gstreamer pipeline that can produce a video like the one you're shown there. I think you are really just mixing 3 videos together instead of two (one is just a loop video).
