### ISSUE TITLE
Python API should have a requirements.txt file

### ISSUE THREAD

**Issue by mithro** [timvideos/gst-switch#128]
https://pip.readthedocs.org/en/1.1/requirements.html

**Comment by MaZderMind** [comment]
While working on the Python-GUI I did not find any python dependencies that would need to be installed by pip, so we may be better of building a debian-package at some point which depends on the required packages.

**Comment by mithro** [comment]
@MaZderMind - we should do both. Not having a requirements.txt file is bad style from a Python point of view.

**Comment by leesdolphin** [comment]
I think even an empty requirements file would be a good option(and maybe a comment as to why it is empty). Then I think that a `setup.py` and/or a `setup3.py` should also be added so that we at least somewhat conform to python library standards.

**Comment by mithro** [comment]
It looks like there is a requirements.txt in the top level directory https://github.com/timvideos/gst-switch/blob/master/requirements.txt

**Comment by mithro** [comment]
It's missing things like gtk/dbus/etc though?

**Comment by hyades** [comment]
that one is for Travis.
