### ISSUE TITLE
Memory leak in gst-switch-srv when doing 720p recording

### ISSUE THREAD

**Issue by mithro** [timvideos/gst-switch#129]
**1726008**

```
videote+ 21580 99.2 21.1 4895556 1726008 pts/0 Sl+  17:09   4:59          |   |       \_ ./tools/gst-switch-srv -f 720p50 -r
```

**1767500**

```
videote+ 21580 99.2 21.6 4895556 1767500 pts/0 Sl+  17:09   5:10          |   |       \_ ./tools/gst-switch-srv -f 720p50 -r
```

**1789828**

```
videote+ 21580 99.0 21.9 4961092 1789828 pts/0 Sl+  17:09   5:27          |   |       \_ ./tools/gst-switch-srv -f 720p50 -r
```

**Comment by mithro** [comment]
@hyades and @deeprave - You guys looked into this, did you get anywhere?

**Comment by deeprave** [comment]
Seems that it is tied to connection to the UI.  Memory is released, presumably via finalize when the UI process disconnects, so it is almost certainly tied to the composite pipeline. Valgrind is providing too much noise to be useful in diagnosing this, so I'm in the process of suppressing lots to get to the cause.

**Comment by mithro** [comment]
So it doesn't consume the ram without the UI connected?

**Comment by mithro** [comment]
Can we temporarily solve the issue by disconnecting and reconnecting the UI?
