### ISSUE TITLE
gstworker.c:484:error: output: (RESOURCE: 5) Could not open resource for reading.

### ISSUE THREAD

**Issue by deeprave** [timvideos/gst-switch#137]
I'm investigating the cause of this error which seems to always occur at startup - the incongruity of 'output' (name of the gstreamer worker) and the message 'could not open resource for _reading_' caught my eye...

The server starts the output worker from gst_switch_server_create_output(), which seems like it should succeed but just not be connected to anything. Perhaps someone more familiar with the server process and how the "output" worker is used can offer some useful insight? The source comments suggest this is related to composite out?

**Comment by deeprave** [comment]
Addendum: commenting out the call to create the "output" worker and the ~8 functions of dead code that results has no operational effect (on the demo). Presumably this worker and associated code is actually unused.

**Comment by mithro** [comment]
This might be related to some of the questions highlighted in https://github.com/timvideos/gst-switch/pull/135
