### ISSUE TITLE
Integration tests should use pyvirtualdisplay or similar module

### ISSUE THREAD

**Issue by mithro** [timvideos/gst-switch#166]
Currently running `make integration` in the python-api directory causes a bunch of X windows to be started. This is kind of annoying. Instead we should use something like xvfb or xvncserver to make the tests independent of the running display. The [PyVirtualDisplay](https://pypi.python.org/pypi/PyVirtualDisplay/0.1.5) module seems like a good idea.

This would also mean that things like the running window manager and other desktop environment things can't affect the test output.

**Comment by MaZderMind** [comment]
It shouldn't ne required to interact with X anyhow. Just calling `tcpclientsrc ! gdpdepay ! pngenc` should be enough.

**Comment by mithro** [comment]
You are correct that most tests don't actually need an xserver. Changing to something like the above pipeline is found in https://github.com/timvideos/gst-switch/issues/37

Any integration test which wants to test the UI is going to need an X server. Testing UI is pretty hard though, so there probably aren't going to be many of these tests. I do think we want to make sure that connecting the UI doesn't cause the server to crash though :)
