### ISSUE TITLE
`NUM` and `FACTOR` stuff in test_controller is incomprehensible

### ISSUE THREAD

**Issue by mithro** [timvideos/gst-switch#170]
I'm trying to understand the tests in test_controller.py and there is all this multiplying by NUM and FACTOR stuff without any explaination on why it is being done. 

NUM and FACTOR always seem to be the value `1` too.

Is this some type of py.test magic or something?

Example below;
```python
class TestGetComposePort(object):

    """Test get_compose_port method"""
    NUM = 1
    FACTOR = 1

    def get_compose_port(self):
        """Create Controller and call get_compose_port method"""
        res = []
        controller = Controller()
        controller.establish_connection()
        for _ in range(self.NUM * self.FACTOR):
            res.append(controller.get_compose_port())
        return res
```

**Comment by hyades** [comment]
@mithro 
I had thought that we can increase the comprehensiveness of the tests by increasing these two factors. 
`NUM` in general is just a value which I use to vary the test inputs and `FACTOR` is the number of times the test is ran for each value produced by `NUM`.
eg.
if I am testing `get_compose_port `, I would ideally vary the testcases to produce different values of the output. This will be done using `NUM`. And using each value of `NUM`, I would run the test `FACTOR` times.

**Comment by mithro** [comment]
This should really be handled at an upper layer than this area.

**Comment by hyades** [comment]
@mithro so what do you think, we should have them properly or completely remove them?
