### ISSUE TITLE
Python API doesn't provide "role" interface

### ISSUE THREAD

**Issue by mithro** [timvideos/gst-switch#172]
When a new control connection is made to the server, it tried to do a callback to determine the role of the connection. The Python API doesn't appear to be providing the required dbus method the server calls.

I believe this interface is also needed to get notified when a new source is added to the system.

```
gst-switch-srv/gstswitchcontroller.c:559:info: calling: info.duzy.gst.switch.SwitchControllerInterface/role
gst-switch-srv/gstswitchcontroller.c:584:error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'info.duzy.gst.switch.SwitchUIInterface' on object at path /info/duzy/gst/switch/SwitchUI (role)
gst-switch-srv/gstswitchcontroller.c:559:info: calling: info.duzy.gst.switch.SwitchControllerInterface/role
gst-switch-srv/gstswitchcontroller.c:584:error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'info.duzy.gst.switch.SwitchCaptureInterface' on object at path /info/duzy/gst/switch/SwitchCapture (role)
gst-switch-srv/gstswitchcontroller.c:391:error: unknown role: 0
```

See the https://github.com/timvideos/gst-switch/blob/master/tools/gstswitchclient.c code.

**Comment by mithro** [comment]
@hyades

**Comment by MaZderMind** [comment]
I'm on that an will report back if I have issues fixing it. This seems to also be the basic cause of #143

**Comment by mithro** [comment]
@MaZderMind  Can you dump your problems with dbus under python that you commented on in IRC into this issue?

**Comment by MaZderMind** [comment]
Short: Currently it is not possible to implement this in Python. I think this is a misconception on the way the DBus-Interface is implemented in gst-switch-srv.

As I understand DBus, it implements a bidirectional client-server rpc-architecture. A Server can register one or more objects on the bus. A client can call methods on these objects, which can return values. A client can also subscribe to signals on these objects. When a server emits a signal it's distributed on the bus like a multicast-message - the server has no way of detecting if and how many clients received it.

gst-switch-srv doesn't follow the client-server paradigm and doesn't use signals. Instead it requires the client to also expose an object and keeps its own list of currently connected clients. This resulted in #143 where the client-connection to the DBus did not last long enough for the server to establish a reverse connection to the clients' exposed object. While this seems awkward, in consideration of the fact that DBus offers the elegant was of using signals to push information to clients without keeping a list of currently connected clients, it becomes a major issue in python:

The Gio-DBus implementation, which is the [recommended way](http://www.freedesktop.org/wiki/Software/DBusBindings/) of communicating with DBus from python, seem to not implement the required methods to expose objects from python ([Question on stackoverflow](https://stackoverflow.com/questions/28030314/registering-an-object-on-dbus-using-pythons-gio-bindings), [Unanswered mail on mail.gnome.org](https://mail.gnome.org/archives/python-hackers-list/2012-May/msg00012.html), [Comment on piware.de](http://www.piware.de/2011/01/na-zdravi-pygi/comment-page-1/#comment-11581)), despite the [Python-Docs](https://lazka.github.io/pgi-docs/#Gio-2.0/structs/DBusInterfaceVTable.html) not mentioning it.

I'd suggest dropping the requirement of clients to expose their own objects but instead use signals to inform interested clients of changes (new source, changed composition-mode). To prove that this would work with C and Python I implemented [a small example](https://github.com/MaZderMind/dbus-signal). This would also simplify the code in [gstswitchcontroller.c](https://github.com/timvideos/gst-switch/blob/master/tools/gstswitchcontroller.c).

It would on the other hand break the existing api and also require some refactoring in [gstswitchcontroller.c](https://github.com/timvideos/gst-switch/blob/master/tools/gstswitchclient.c) and maybe other files.

**Comment by mithro** [comment]
Can you link some more information on the signals side of things?

If your understanding is correct, it does sound like we should be changing the way the controller stuff works to use the broadcast signals for doing things like port changes and such.

**Comment by hyades** [comment]
@MaZderMind +1. Signals can very well handle this. 
But this wont allow us to send custom information to a type of a client (Though there is a workaround for this). Also signals dont have a response, so wondering if this could produce any condition where the UIs could go out of sync if they miss out on a signal.

**Comment by MaZderMind** [comment]
Why would you direct signals *of the same name* to only one type of client?
If they had different names it would be easy for the Client to filter out what he thinks he needs.

Another way would be to use two different Object-Paths on the Server-Side to emit signals for specific client-types. the object_path is something a Client can filter for when subscribing to signals.

**Comment by MaZderMind** [comment]
Unfortunately it's actually not that easy. When starting one's one GDBusServer to a) be independent of the system's dbus configuration and b) guarantee to accept commands via network (see #175), this Server will (quoting the docs) "will not perform message routing or implement the org.freedesktop.DBus interface."

In other words: it is not possible to start a Server and then simply connect as a client to it and offer an interface. The presence of that interface and any signals that it sends will not be routed to other connected clients, which essentially means that it's not a multi-consumer bus anymore and signals are not multicast anymore.

In fact is is required that the program creating the DBus-Server manages a list of all currently connected clients and if a signal should be raised, so so by iterating over all clients, which is very close to what gst-switch-srv actually does.

The only difference remaining is, that currently gst-switch-srv relies on the client itsself exposing object, which is still not possible with python. If the server would be changed to use signals instead, interaction with python would be possible. I've proven that in https://github.com/MaZderMind/dbus-signal where `dbus-signal-ownsrv` mimics `gst-switch-srv` while `dbus-signal-ownsrv.py` takes the GUIs role.

**Comment by mithro** [comment]
Sounds like you have a good handle on the issue. Happy for you to proceed
along the vain of the example.

Sorry about this issue, didn't realise how much was still missing from the
API.

**Comment by MaZderMind** [comment]
In one of the Line-Notes in #184 @mithro requested a way for the client to tell the Server a Role. I'd suggest to implement this as a server-call that takes a String, something like a HTTP User-Agent-String.

The Server would store this as part of the Connection and use it in the Logs. It would default to something like "Unknown Client" which would hint the Client-Author that he can set it if he wants it.

I'd opt for keeping it optional.

**Comment by mithro** [comment]
Sounds good to me.
