### ISSUE TITLE
gst-switch-srv should either use the Session-DBus or open its DBus-Server via TCP

### ISSUE THREAD

**Issue by MaZderMind** [timvideos/gst-switch#175]
While DBus allows an application to create its own Server, this is an unusual use-case. Most of the time server and client connect to the System-Wide or the Session-Wide Message-Bus Deamon. These Daemons can also be exported via TCP to be accessable from another location, but this is a system-configuration thing.

gst-switch-srv creates its own server which listens on a unix domain-socket. This itself is not wrong but also seems quite unusual and does not match the remaining parts of gst-switch that listens on TCP.

gst-switch-srv should either use the Session-DBus or open its DBus-Server via TCP.

**Comment by MaZderMind** [comment]
Forget to add: I'd opt for listening on TCP with 0.0.0.0 (or better ::1) as the interface, which would allow remote control of gst-switch-srv from the network. If gst-switch-srv is being ran in an unsafe network environment it's the task of the operator to install a firewall on the system running gst-switch-srv that forbids connections from undesired sources.

**Comment by mithro** [comment]
The dbus bus should already be listening on the `--control-port`?

**Comment by MaZderMind** [comment]
It does listen there but connections to this port are not handled yet:
https://github.com/timvideos/gst-switch/blob/master/tools/gstswitchserver.c#L780

So I'd suggest instead of running the local DBus-Server on a unix-socket, we should use this port to bind the DBus-Server to.
