### ISSUE TITLE
Figure out the missing video frames

### ISSUE THREAD

**Issue by mithro** [timvideos/gst-switch#19]
The frame strips are missing video frames. Find out what happened to them and fix.

Current theories include;
- inter doesn't have enough slack in the frame delay.
- missing frames are not created by the test src.

**Comment by mithro** [comment]
@hyades has been looking into this, can you dump some details about when frames are going missing plus some status of your testing scripts?

**Comment by hyades** [comment]
@mithro Added all the relevant documentation to reproduce the frame drop at https://gist.github.com/hyades/546512eaf028e1495814
(The tar file is getting uploaded)
