### ISSUE TITLE
gst-switch doesn't compile on Debian "jessie" (the next stable release)

### ISSUE THREAD

**Issue by mithro** [timvideos/gst-switch#199]
gst-switch uses a number of functions deprecated in gtk+-3.14 - as we compile with -Werror, this means that gst-switch will fail to compile.

The functions appear to be;
- gtk_widget_get_double_buffered, 
- gtk_misc_set_alignement, 
- gtk_misc_get_type

My guess is this related to the old UI.

**Comment by MaZderMind** [comment]
I'd rather finish the work on #140 (Python GUI) and remove the C-GUI Code completely.
