### ISSUE TITLE
Composite-Output is 30fps, independent of configured format

### ISSUE THREAD

**Issue by MaZderMind** [timvideos/gst-switch#200]
Independent of the Video-Format selected, the Composite-Output and the Recorging-Output are always 30fps, while the Preview-Sinks' framerate depend on the specified format.

For example with `-f debug` the Preview-Sinks are 25fps while the recording is 30fps, but also for `-f '1280x720@60'` the recording will be in 30fps even if the inputs can supply twice the numer of frames.

I'm unsure if this is expected or a bug.

**Comment by mithro** [comment]
This is unexpected, the recording format should be exactly the specified input format.

How are you testing this?

**Comment by mithro** [comment]
Looking at the gst-switch output, the following occurs;
```
gst-switch-srv/gstrecorder.c:283:info: Recording to recording-tansell-z620-l2.syd.corp.google.com-20150423-130021.mkv and port 3002
gst-switch-srv/gstrecorder.c:314:info: Recording pipeline
----
intervideosrc name=source_video channel=composite_video ! video/x-raw,width=300,height=200 ! queue ! jpegenc quality=100 ! mux. 
interaudiosrc name=source_audio channel=composite_audio ! queue ! mux. 
matroskamux name=mux streamable=true  writing-app='gst-switch' min-index-interval=1000000 ! tee name=result 
result. ! queue max-size-buffers=1 ! filesink name=disk_sink sync=false location="recording-tansell-z620-l2.syd.corp.google.com-20150423-130021.mkv" result. ! queue max-size-buffers=1 ! gdppay ! tcpserversink name=tcp_sink sync=false port=3002 
---
```

**Comment by mithro** [comment]
I have confirmed that this is a problem using the avprobe tool;
```
$ avprobe recording-tansell-z620-l2.syd.corp.google.com-20150423-130021.mkv 
avprobe version 9.18-6:9.18-0ubuntu0.14.04.1, Copyright (c) 2007-2014 the Libav developers
  built on Mar 16 2015 13:19:10 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
[matroska,webm @ 0x10cb200] Estimating duration from bitrate, this may be inaccurate
Input #0, matroska,webm, from 'recording-tansell-z620-l2.syd.corp.google.com-20150423-130021.mkv':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0.0(eng): Video: mjpeg, yuvj420p, 300x200 [PAR 1:1 DAR 3:2], 30 fps, 30 tbr, 1k tbn (default)
    Metadata:
      title           : Video
    Stream #0.1(eng): Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s (default)
    Metadata:
      title           : Audio
# avprobe output
```

The problem is that the command line caps are not getting added to the recording pipeline in [gst_recorder_get_pipelinestring in gstrecorder.c](https://github.com/timvideos/gst-switch/blob/master/tools/gstrecorder.c#L290). 

Should be a simple fix of just calling `gst_switch_server_get_video_caps_str` function (see usage in the [gstcase.c file](https://github.com/timvideos/gst-switch/blob/master/tools/gstcase.c#L286)) rather than generating the caps manually, will upload one shortly. 

Probably should add a test which looks at the recorded file video output using something like avprobe.

**Comment by MaZderMind** [comment]
The new int tests do Test for this by expecting caps on the output ports - this is how I noticed it.

The corresponding test is currently on fail with a reference to this ticket.

**Comment by mithro** [comment]
Awesome, I'll merge your pull request (after review) and then send my own pull request which fixes this issue.
