### ISSUE TITLE
Audio-Spectrum differs on travis

### ISSUE THREAD

**Issue by MaZderMind** [timvideos/gst-switch#207]
The integration-tests use a command like this to identify audio-streams passing through gst-switch:

```
gst-launch-1.0
    tcpclientsrc num-buffers=75 host=localhost port=3003 !
    gdpdepay !
    spectrascope shader=none !
    video/x-raw,width=400,height=200 !
    videoconvert !
    pngenc !
    multifilesink location=frame%u.png
```

When ran on travis, the spectrum looks like this:

![](http://i.imgur.com/cB14zNM.png)

While locally the spectrum looks like this:

![](http://i.imgur.com/el5xTRI.png)

I guess the distortion originates from jaggy audio output (ie dropouts in the audio) which represent high frequency content in the spectral domain.

The relevant test is set to xfail and references this issue.

**Comment by mithro** [comment]
Have you tried uploading the raw audio files? Looking at them would quickly show if there are periods of empty audio or other similar issues.
