### ISSUE TITLE
Need a way to identify all input coming from a single computer/source

### ISSUE THREAD

**Issue by mithro** [timvideos/gst-switch#22]
A single computer could be sending;
- Video
- Audio
- Face information

Need some way to "group" them into the UI so it's clear where they are coming from.

Open Questions:
- What happens when there are multiple video sources connected to a single computer? 
- Maybe we need levels of grouping? IE Computer, input source, etc?
- How is this information sent to the gst-switch server?

**Comment by MaZderMind** [comment]
If possible this information should be passed as metadata with the gdp-stream, maybe embedded using the taginject plugin: http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-taginject.html
