### ISSUE TITLE
Install instructions too complex

### ISSUE THREAD

**Issue by CarlFK** [timvideos/gst-switch#28]
Current install instructions have way too many git clone, including 

git clone https://github.com/hyades/gst-switch.git
and building that not  timvideos/gst-switch

Here is my start:
```
# git clone https://github.com/timvideos/gst-switch.git

sudo apt-get install libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev 

cd gst-switch
./autogen.sh 
make
```

**Comment by mithro** [comment]
@CarlFK confirms he is happy this doesn't suck any more, closing.
