### ISSUE TITLE
740x480 causes broken video

### ISSUE THREAD

**Issue by CarlFK** [timvideos/gst-switch#32]
#!/bin/bash -ex

cd tools

```
./gst-switch-srv &
sleep 5
./gst-switch-ui &
sleep 3
gst-launch-1.0 videotestsrc pattern=smpte is-live=1 \
        ! clockoverlay time-format="%S" font-desc="Sans 240" \
        ! video/x-raw, width=740, height=480 \
        ! gdppay \
        ! tcpclientsink port=3000 \
& lnch=$!
```

![gsts6](https://cloud.githubusercontent.com/assets/23225/4917962/c09d68f8-64eb-11e4-996e-fee34acac8df.png)

**Comment by mithro** [comment]
For this to be fixed it needs https://github.com/timvideos/gst-switch/issues/108 and https://github.com/timvideos/gst-switch/issues/95 should finished.

**Comment by mithro** [comment]
This has now been fixed! @CarlFK can you please verify?
