### ISSUE TITLE
empty thumb

### ISSUE THREAD

**Issue by CarlFK** [timvideos/gst-switch#44]
![screenshot from 2014-12-03 21 12 11](https://cloud.githubusercontent.com/assets/23225/5293089/16eaa90e-7b31-11e4-8198-c690ced4937f.png)

Not always reproducible, but seems to happen over 80%.
Not sure what the pattern is.

Same sources. 
using dvsmon.py, hitting kill/run a few times will fix or cause it.

```
+ ./dvs-mon.py -c gswitch.py
Executed:  gst-switch-srv --record foo
Executed:  gst-switch-ui
Executed:  gst-launch-1.0 videotestsrc pattern=18 is-live=1     ! video/x-raw, width=300, height=200     ! gdppay     ! tcpclientsink port=3000
Executed:  gst-launch-1.0 videotestsrc pattern=18 is-live=1     ! video/x-raw, width=300, height=200     ! gdppay     ! tcpclientsink port=3000
```

**Comment by mithro** [comment]
@CarlFK can you try and repo this again in a couple of days.

**Comment by mithro** [comment]
@CarlFK are you still able to repo this?

**Comment by CarlFK** [comment]
yes.

![screenshot from 2015-04-27 14 28 33](https://cloud.githubusercontent.com/assets/23225/7355951/d37c8350-ecea-11e4-99de-9485a819c528.png)
