### ISSUE TITLE
Mode of A/B compositing needs better UI control 

### ISSUE THREAD

**Issue by CarlFK** [timvideos/gst-switch#45]
Tab   Change a mode of A/B compositing, stroking it repeatly will cycle within modes  and off.  

That seems pretty much un-useable.  There are 4 modes.  to get from mode 3 back to 2, you need to hit tab 3 times which flicks over modes 4,1,2 which is pretty bad.

My guess is 4 buttons: mode: 1,2,3,4

**Comment by mithro** [comment]
I believe this is fixed. There is a separate issue at https://github.com/timvideos/gst-switch/issues/46 about adding buttons for this.
