### ISSUE TITLE
UI buttons

### ISSUE THREAD

**Issue by CarlFK** [timvideos/gst-switch#46]
The UI needs buttons for all the controls.  Keyboard shortcuts are good, but I don't see anyone being able to learn them.  

A volunteer at a conference will have 5-30 minutes of explanation and some time to try it out, then the talk starts.  I can't imagine someone being able to figure out what key to press.  even having a laminated cheat sheet next to them seems bad.

**Comment by MaZderMind** [comment]
despite a better GUI we have used special keyboards where we ripped out all keys not needed and labeld the remaining ones. Much easier to learn for volunters.

**Comment by mithro** [comment]
Got a photo?

I know lots of other crews are into MIDI controllers but they seem even
more intimidating for us non-A/V background people.

I was thinking that a touchscreen might be the easiest way for everything
apart from PIP placement. Making PIP always appear at a static location
solves that issue, specially if there is no overlap.
