### ISSUE TITLE
--record should work without an argument (and provide a default value for filenames)

### ISSUE THREAD

**Issue by CarlFK** [timvideos/gst-switch#48]
gst-switch/tools/gst-switch-srv --record 
./tools/gstswitchserver.c:115:error: option parsing failed: Missing argument for --record

It would be nice if I didn't have to provide a filename.
Yes it is easy, but so is setting a default, which I would find better.   either a constant, or my preference would be to use the machine's hostname.    I set the hostname to the room the machine is recoding, so having the files in a dir named after the room is desirable.

**Comment by mithro** [comment]
Fixed.
