### ISSUE TITLE
Should have a gst-switch-command tool

### ISSUE THREAD

**Issue by mithro** [timvideos/gst-switch#54]
It would be really nice to have a gst-switch-command tool which let you issue commands to the gst-switch-server. Some example of these tools are [`virsh` ](http://linux.die.net/man/1/virsh) or https://whatbox.ca/wiki/Deluge_Console_Documentation

The tool should operate in two modes;
- "One shot mode" - When given enough arguments on the command line, it should connect to the gst-switch-srv and then perform the operation and exit. The exit code should report if the command was successful for not.
- "Console mode" - When not given any arguments it should start up a readline style console. There you can run all the same commands as the command line mode but it doesn't exit until you type "quit" or something.

@hyades This would be trivial to do with the Python-API right? How long do you think it would take to whip up the one-shot-mode? It would be awesome if the command line arguments could be automagically generated from the Python-API.....

**Comment by mithro** [comment]
Start of this work is at https://github.com/timvideos/gst-switch/pull/92

**Comment by mithro** [comment]
Initial version of this was created in https://github.com/timvideos/gst-switch/pull/121

@hyades does your console script support "oneshot" mode, or just the "console mode" described above?

**Comment by hyades** [comment]
@mithro no its only console mode. Oneshot mode is currently not present.
