### ISSUE TITLE
Server crashes after repeated connections with the UI 

### ISSUE THREAD

**Issue by hyades** [timvideos/gst-switch#63]
The script I ran is - (in the gst-switch/ directory)
```bash
#!/bin/bash -ex

cd tools

./gst-switch-srv &
sleep 5

for (( i = 0; i < 10; i++ )); do
	 ./gst-switch-ui &
	sleep 5
	kill $!
done

ps -ef | grep gst-switch-srv

```
The server crashes after certain iterations of the loop.
Output at http://paste.ubuntu.com/9414954/.

**Comment by mithro** [comment]
@hyades - Did we end up fixing this now?

**Comment by hyades** [comment]
@mithro yea should be fixed in the pull request.

**Comment by mithro** [comment]
@hyades means https://github.com/timvideos/gst-switch/pull/92

**Comment by mithro** [comment]
This was fixed in https://github.com/timvideos/gst-switch/pull/106
