### ISSUE TITLE
file duration algorithm  

### ISSUE THREAD

**Issue by CarlFK** [timvideos/gst-switch#84]
I need to figure out how long the output file is (in seconds) 
  
I am hoping gst-switch-srv can somehow write it out to a header, or maybe some way of looking at the tail of the file, like does each frame have a time stamp?

If none of this is possible, writing out times to a cutlist.txt file is worth considering.  Relying on the next file name to tell me the duration of the previous one seems dangerous.  

$ gst-switch-srv --record foo
let it run for a bit, ^c.  this creates a .avi file.  rename it to foo.avi

(05:19:08 PM) mithro: CarlFK: okay, my guess is that gstreamer isn't writing out the index after closing the file

carl@twist:~/src/dvsmon$ avconv -i foo.avi 
avconv version 9.16-6:9.16-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Aug 10 2014 18:16:02 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
Input #0, avi, from 'foo.avi':
  Duration: 00:00:00.00, start: 0.000000, bitrate: -2147483 kb/s
    Stream #0.0: Video: vp8, yuv420p, 300x200, 30 fps, 30 tbr, 30 tbn
    Stream #0.1: Audio: aac, 48000 Hz, stereo, fltp

$ melt foo.avi -consumer xml
some interesting lines:

  <profile description="automatic" width="300" height="200" progressive="1" sample_aspect_num="1" sample_aspect_den="1" display_aspect_num="300" display_aspect_den="200" frame_rate_num="30" frame_rate_den="1" colorspace="601"/>

<tractor id="tractor0" title="foo.avi" global_feed="1" in="0" out="2147483646">

**Comment by mithro** [comment]
@thaytan promised to work on fixing this today (2015-01-10) at the sprints.
